#!/usr/bin/ruby

pow_name = 'highrise-marketing'

puts "Installing/Upgrading Pow"
`curl get.pow.cx | sh`
puts " -> done"

puts "Configuring Pow"
if File.exist?(File.expand_path("~/.pow/#{pow_name}"))
  `rm ~/.pow/#{pow_name}`
end
`ln -fs #{File.expand_path(__dir__ + '/..')} ~/.pow/#{pow_name}`
puts " -> done"

puts "Installing Bundler"
`gem install bundler`
puts " -> done"

puts "Install Ruby Gems"
`bundle install`
`rbenv rehash`
puts " -> done"
